name = "acmaxconjecture_arxiv_v2"
version = "0.1.0"
defaultTargets = ["ACMaxConjecture"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "ACMaxConjecture"
